Change binding on Hide REPL to ^s
swarm-game/swarm pull request #1375
Opened 2023-07-17 15:36 UTC by noahyor

Fixes #1325.

2023-07-18 05:28 UTC, kostmo requested changes

2023-07-18 05:28 UTC, kostmo commented on src/Swarm/TUI/Controller.hs
> +    ControlChar ',' -> do
I just realized that, unfortunately, `CTRL + comma` is [not handled properly by the terminal](https://stackoverflow.com/a/7544277/105137).

However `ALT + comma` does work.  So we could change this to 
```suggestion
    MetaChar ',' -> do
```

2023-07-18 05:30 UTC, kostmo commented on src/Swarm/TUI/View.hs
> +      , Just (NoHighlight, "^,", if s ^. uiState . uiShowREPL then "hide REPL" else "show REPL")
The `Alt` key is the same as `Meta`, so this should be:
```suggestion
      , Just (NoHighlight, "M-,", if s ^. uiState . uiShowREPL then "hide REPL" else "show REPL")
```

2023-07-18 05:31 UTC, kostmo commented
Thank you for pushing this one along!

2023-07-19 03:04 UTC, kostmo approved these changes

2023-07-19 11:45 UTC, byorgey approved these changes
I tested the new `M-,` , seems to work.

2023-07-19 15:52 UTC, merged